//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace wcfmayoreoc
{
    using System;
    using System.Collections.Generic;
    
    public partial class carritos
    {
        public int idcarritos { get; set; }
        public Nullable<System.DateTime> fechaCreacion { get; set; }
        public Nullable<int> cantidad { get; set; }
        public Nullable<decimal> total { get; set; }
        public Nullable<System.DateTime> caducidad { get; set; }
        public int clientes_idcliente { get; set; }
        public int productos_idproducto { get; set; }
    
        public virtual clientes clientes { get; set; }
        public virtual productos productos { get; set; }
    }
}
