//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace wcfmayoreoc
{
    using System;
    using System.Collections.Generic;
    
    public partial class cortecaja
    {
        public int idcortecaja { get; set; }
        public Nullable<System.DateTime> fecha { get; set; }
        public string encargado { get; set; }
        public Nullable<decimal> fondoInicial { get; set; }
        public Nullable<decimal> ingresoTotal { get; set; }
        public Nullable<decimal> efectivoCaja { get; set; }
    }
}
