//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace wcfmayoreoc
{
    using System;
    using System.Collections.Generic;
    
    public partial class cuentasbancarias
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public cuentasbancarias()
        {
            this.pagos = new HashSet<pagos>();
            this.ordencompra = new HashSet<ordencompra>();
        }
    
        public int idcuentaBancaria { get; set; }
        public Nullable<int> numeroCuenta { get; set; }
        public string sucursal { get; set; }
        public string titular { get; set; }
        public Nullable<int> clabe { get; set; }
        public string banco { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<pagos> pagos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ordencompra> ordencompra { get; set; }
    }
}
