//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace wcfmayoreoc
{
    using System;
    using System.Collections.Generic;
    
    public partial class ordencompra
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ordencompra()
        {
            this.envios = new HashSet<envios>();
            this.pagos = new HashSet<pagos>();
            this.productos1 = new HashSet<productos>();
        }
    
        public int idordenCompra { get; set; }
        public string domicilioEntrega { get; set; }
        public Nullable<System.DateTime> fecha { get; set; }
        public string cantidad { get; set; }
        public string total { get; set; }
        public string pesototal { get; set; }
        public string pagado { get; set; }
        public string paqueteria { get; set; }
        public int clientes_idcliente { get; set; }
        public int productos_idproducto { get; set; }
        public int cuentasbancarias_idcuentaBancaria { get; set; }
    
        public virtual clientes clientes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<envios> envios { get; set; }
        public virtual productos productos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<pagos> pagos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<productos> productos1 { get; set; }
        public virtual cuentasbancarias cuentasbancarias { get; set; }
    }
}
