//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace wcfmayoreoc
{
    using System;
    using System.Collections.Generic;
    
    public partial class pagos
    {
        public int idpagos { get; set; }
        public string concepto { get; set; }
        public Nullable<decimal> monto { get; set; }
        public string notas { get; set; }
        public int clientes_idcliente { get; set; }
        public int ordencompra_idordenCompra { get; set; }
        public int cuentasbancarias_idcuentaBancaria { get; set; }
        public int metodospago_idmetodoPago { get; set; }
    
        public virtual clientes clientes { get; set; }
        public virtual cuentasbancarias cuentasbancarias { get; set; }
        public virtual metodospago metodospago { get; set; }
        public virtual ordencompra ordencompra { get; set; }
    }
}
