//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace wcfmayoreoc
{
    using System;
    using System.Collections.Generic;
    
    public partial class productos
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public productos()
        {
            this.carritos = new HashSet<carritos>();
            this.ordencompra = new HashSet<ordencompra>();
        }
    
        public int idproducto { get; set; }
        public string codigoInterno { get; set; }
        public string codigoProveedor { get; set; }
        public Nullable<int> peso { get; set; }
        public string descripcion { get; set; }
        public Nullable<int> existencia { get; set; }
        public string productoscol { get; set; }
        public string imagen1 { get; set; }
        public string imagen2 { get; set; }
        public string imagen3 { get; set; }
        public string imagen4 { get; set; }
        public Nullable<bool> nuevo { get; set; }
        public Nullable<decimal> precio { get; set; }
        public string categoriaPrecio { get; set; }
        public Nullable<bool> agotado { get; set; }
        public int catalogos_idcatalogo { get; set; }
        public int categorias_idcategoria { get; set; }
        public int subcategorias_idsubcategorias { get; set; }
        public int ordenCompra_idordenCompra { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<carritos> carritos { get; set; }
        public virtual catalogos catalogos { get; set; }
        public virtual categorias categorias { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ordencompra> ordencompra { get; set; }
        public virtual ordencompra ordencompra1 { get; set; }
        public virtual subcategorias subcategorias { get; set; }
    }
}
